# Python for Data Analytics
## Week 4 lab: Numerical Python with NumPy

### Review Week 4 presentation notebooks

# Exercises

Please organise your solutions as a separate notebook and upload to the LMS (Moodle):
* Notebook (.ipynb)
* Generate pdf (File -> Download as -> PDF).

### EXERCISE 1

Create:
1. A three-dimensional NumPy array of zeros
2. A two-dimensional NumPy array of random integer numbers (from a given range)
3. A three-dimensional NumPy array with first 27 prime numbers (you can use a primePy package or just enter them manually)



In [10]:
import numpy as np

!pip install primePy
from primePy import primes

matrix1 = np.zeros((3,3,3))
range_start = input("Enter the range start: ")
range_end = input("Enter the range end: ")
matrix2= np.random.randint(range_start,range_end,(3,3))
prime_list = primes.first(27)
matrix3 = np.array(prime_list).reshape((3,3,3))

print(matrix1)
print (matrix2)
print (matrix3)

Enter the range start: 5
Enter the range end: 20
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[ 9 13 12]
 [15 17 18]
 [ 7 12 18]]
[[[  2   3   5]
  [  7  11  13]
  [ 17  19  23]]

 [[ 29  31  37]
  [ 41  43  47]
  [ 53  59  61]]

 [[ 67  71  73]
  [ 79  83  89]
  [ 97 101 103]]]


### EXERCISE 2

Write a programme to replace zeros with np.nan values in a given NumPy array


In [18]:
import numpy as np
m_nan = np.array([[1, 0, 3],
                [0, 5, 6],
                [7, 8, 0]], dtype=float)
m_nan[m_nan==0] = np.nan
print(m_nan)

[[ 1. nan  3.]
 [nan  5.  6.]
 [ 7.  8. nan]]


### EXERCISE 3

Create a NumPy array of booleans and illustrate the following methods
1. .any()
2. .all()

Apply these methods for the complete array and by every dimension (e.g., by rows)



In [1]:
import numpy as np

arr = np.array([[True,  False, True],
                [False, False, True],
                [True,  True,  True]])

print("Array:\n", arr)
print("any():", arr.any())
print("all():", arr.all())
print("\n--- By rows (axis=1) ---")
print("any:", arr.any(axis=1))
print("all:", arr.all(axis=1))
print("\n--- By columns (axis=0) ---")
print("any:", arr.any(axis=0))
print("all:", arr.all(axis=0))


Array:
 [[ True False  True]
 [False False  True]
 [ True  True  True]]
any(): True
all(): False

--- By rows (axis=1) ---
any: [ True  True  True]
all: [False False  True]

--- By columns (axis=0) ---
any: [ True  True  True]
all: [False False  True]


### EXERCISE 4

Create two 4x4 NumPy arrays of random numbers from the range [0,100].
Create a boolean mask from the second array, which is 1 for all value more than 50 and 0 otherwise and use it to filtering the first array (replace elements, where mask is 0, with zetos).



In [15]:
import random
import numpy as np

arr1 = np.random.randint(0,100,(4,4))
arr2 = np.copy(arr1)
arr2[arr2>50]=1
arr2[arr1<=50]=0
maskek = np.where(arr2,arr1,0)
print(maskek)
#print(arr1)
#print(arr2)


[[70  0  0  0]
 [78 51  0  0]
 [ 0 69 63  0]
 [ 0  0 53 63]]


### EXERCISE 5

Write a  program to compute the mean, median, standard deviation, and variance of a given NumPy array along the second axis and provide several test cases for the programme. Recall the meaning of mentioned statistical characteristics.



### EXERCISE 6

Write a  program to calculate the difference between the maximum and the minimum values of a given NumPy array along the all available dimensions.

E.g., for a matrix:

[[1, 2, 3]

 [10, 2, 30]

 [5, 20, 10]]


the programme should return:

Axis 0: [2, 28, 15]

Axis 1: [9, 18, 27]


### EXERCISE 7

Create a 7x7 NumPy array of random integers and subset all possible 5x5 sub-arrays (including overlapping ones).

### EXERCISE 8

Write a program that delete duplicates from a NumPy array and a provided dimension (e.g., duplicate rows). Records are duplicates if all value for all other dimensions are the same. Test the programme for 2D and 3D arrays.

### EXERCISE 9

Illustarate solution of 2-3 systems of linear equations from the "Mathematics for Data Analytics" course using np.linalg

### EXERCISE 10

Load numeric data from the CSV file, utilised in Lab 3 Exercise 9 into a NumPy array and calculate its statistics (by columns)

### EXERCISE 11

Using the presentations for this week and any image of your choice, illustrate
1. Loading of an image into a Numpy array
2. Flipping the image (by sorting the array)
3. Rotating the image (by transposing)
4. Filtering R,G,and B colors
5. Clipping a reactangular area the image by slicing
6. Grayscaling of the image by different colour weighting schemes - https://www.johndcook.com/blog/2009/08/24/algorithms-convert-color-grayscale/



### EXERCISE 12

Implement the following procedure for the text of "Alice in Wonderland" (see the Week 3 presentations):
1. Split the text into three pieces with similar number of words: Part1, Part2, Part3
2. For every part calculate the relative frequency of each word (number of word occurances divided by number of words in a Part)
3. Combine frequencies for all parts into NumPy array (the first dimension should correspond to the number of parts, 3)
4. Compare frequencies of word "alice" between the parts
5. Print 10 words with most significant (maximum) change of frequencies between parts
6. Print 10 words with most stable frequency (minimum) between parts

If you are interested in text analysis, read about TF-IDF - e.g., https://towardsdatascience.com/tf-idf-for-document-ranking-from-scratch-in-python-on-real-world-dataset-796d339a4089
